import { Tour } from "./tour/tour.component";

export const tours: Tour[] = [
    {
      id: 1,
      name: 'Hiszpania',
      destination: 'Madryt',
      dateBegin: "2022-12-10",
      dateEnd: "2022-12-19",
      imageURL: "assets/img/tour_pic.jpg",
      places: 7,
      money: 2100.0,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
      display: true,
      rate: 3
    },
    {
        id: 2,
        name: 'Wielka Brytania',
        destination: 'Londyn',
        dateBegin: "2023-01-01",
        dateEnd: "2023-01-13",
        imageURL: "assets/img/tour_pic.jpg",
        places: 10,
        money: 4120.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 3
      },
      {
        id: 3,
        name: 'Włochy',
        destination: 'Rzym',
        dateBegin: "2022-12-21",
        dateEnd: "2022-12-29",
        imageURL: "assets/img/tour_pic.jpg",
        places: 5,
        money: 3450.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 1
      },
      {
        id: 4,
        name: 'Rosja',
        destination: 'Moskwa',
        dateBegin: "2022-01-18",
        dateEnd: "2020-01-28",
        imageURL: "assets/img/tour_pic.jpg",
        places: 7,
        money: 670.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 6
      },
      {
        id: 5,
        name: 'Polska',
        destination: 'Sosnowiec',
        dateBegin: "2022-12-25",
        dateEnd: "2022-12-28",
        imageURL: "assets/img/tour_pic.jpg",
        places: 10,
        money: 700.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 1
      },
      {
        id: 6,
        name: 'Portugalia',
        destination: 'Lizbona',
        dateBegin: "2022-01-20",
        dateEnd: "2020-01-30",
        imageURL: "assets/img/tour_pic.jpg",
        places: 12,
        money: 2100.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 4
      },
      {
        id: 7,
        name: 'Francja',
        destination: 'Paryż',
        dateBegin: "2022-12-25",
        dateEnd: "2020-12-31",
        imageURL: "assets/img/tour_pic.jpg",
        places: 7,
        money: 12100.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 5
      },
      {
        id: 8,
        name: 'Chorwacja',
        destination: 'Split',
        dateBegin: "2023-02-19",
        dateEnd: "2023-02-25",
        imageURL: "assets/img/tour_pic.jpg",
        places: 15,
        money: 1230.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 4
      },
      {
        id: 9,
        name: 'Niemcy',
        destination: 'Berlin',
        dateBegin: "2022-12-21",
        dateEnd: "2022-12-28",
        imageURL: "assets/img/tour_pic.jpg",
        places: 15,
        money: 1230.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 2
      },
      {
        id: 10,
        name: 'Dania',
        destination: 'Kopenhaga',
        dateBegin: "2023-01-19",
        dateEnd: "2023-01-25",
        imageURL: "assets/img/tour_pic.jpg",
        places: 20,
        money: 1800.0,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam egestas.",
        display: true,
        rate: 2
      }
    ]